### ISSUE TITLE
Implement the FLASH/EuXFEL specific trainID reader 

### ISSUE THREAD

**Issue by troehling** [CFEL-CMI/pymepix#29]
Implement the FLASH/EuXFEL specific trainID reader on develop using programmable logic to turn it on (only) when available and wanted.

**Comment by bj-s** [comment]
At XFEL, we are currently testing an alternative `PacketProcessor` and accordingly an alternative Pipeline that supports train IDs supplied via the TDC2 (instead of using the USB stick https://git.xfel.eu/fpga/trainidUSB). Thus it can be turned on by selecting or building an appropriate processing pipeline.

Currently, we just append to the normally returned EventData two arrays. One with the train id and one with a flag to indicate a possible faulty train id. (i.e. 0 = ok, -1 = train id was infered because of failure to interpret the provided signal, -2 = train id could not be determined).

For redundancy we are also keeping the counter.

One limitation of the current implementation is that max. 1 process is supported for the `PacketProcessor`.

One open question is, whether we should integrate this somehow better with the exisiting `MessageType` `EventData` or we should introduce a new `MessageType` (e.g. `TidEventData`).

When this implementation is working properly, it could be relatively easy implemented with the develop branch, since they are only an added pipeline, an added `PacketProcessor` subclass and possibly an added `MessageType`.

**Comment by BenMoon** [comment]
This is kind of solved by adding the 2nd TDC, which is currently been used to encode the trainID.
