### ISSUE TITLE
Data processing in packetprocessor.py

### ISSUE THREAD

**Issue by sebastian-trippel** [CFEL-CMI/pymepix#3]
There are several issues where the data might not be treated correctly in packetprocessor.py

- the 64 timepixdata should not be casted to an uint64
- in correct_global_time(self, arr, ltime) there is the case 0, -2 and 2 for the diff missing
   - 0 might be covered by line 221: globaltime = (ltime & 0xFFFFC0000000) | (arr & 0x3FFFFFFF)
- in find_events_fast the buffer of the data is updated but not the trigger
   - this results in a loss of data
- the way it is written now it also throughs away events where the corresponding trigger arrives later than the pixel events at the edge of the chunk of data that is analysed at once
- we should maybe try to update the buffer and the triggers simultaneously

**Comment by jokuha** [comment]
Hi @sebastian-trippel, it would be useful to first better describe what the problem is – and (only) then provide possible solutions (although – if you know what the solution is – you could simply implement yourself;-).
A bug report is a lot about the 'why' (is it a problem), not so much the "what might be wrong technically". It should also contain clear descriptions on when it happens and how to reproduce it...
Mayer the following is a good entry point for this: https://medium.com/pitch-perfect/how-to-write-the-perfect-bug-report-6430f5a45cd
